src/main/java/com/withus/withmebe/common/aop/LoggingAspect.java

✨ Features: LoggingAspect

---

src/main/java/com/withus/withmebe/common/exception/CustomException.java
src/main/java/com/withus/withmebe/common/exception/CustomExceptionHandler.java
src/main/java/com/withus/withmebe/common/exception/ExceptionCode.java

**TO-BE**
- ExceptionHandler 추가

Feature/exception ExceptionHandler 추가

---

src/main/java/com/withus/withmebe/gathering/controller/GatheringController.java
src/main/java/com/withus/withmebe/gathering/dto/request/AddGatheringRequest.java
src/main/java/com/withus/withmebe/gathering/entity/Gathering.java
src/main/java/com/withus/withmebe/gathering/repository/GatheringRepository.java
src/main/java/com/withus/withmebe/gathering/service/GatheringService.java
src/test/java/com/withus/withmebe/gathering/service/GatheringServiceTest.java

**AS-IS**
- 모임서비스 생성만 구성
- 테스트코드 없음
**TO-BE**
-  모임서비스 API 테스트코드 추가
- 코드 리팩터링
- GatheringController 불필요한 코드삭제
- GatheringService 중복코드 통합
- GatheringDto DB > 자바 어노테이션으로 수정
- GatheringEntity 데이터 추가요청에 따른 필드값 추가
**TEST**
- commentService 테스트코드 구현
- createComment 성공 테스트 추가
- readComments 성공 테스트 추가
- updateComment 성공 테스트 추가
- deleteComment 성공 테스트 추가

🔀 Merge branches Feature/gathering: gathering 모임서비스구현, 테스트코드 추가

---

src/main/java/com/withus/withmebe/gathering/controller/GatheringController.java
src/main/java/com/withus/withmebe/gathering/dto/request/AddGatheringRequest.java
src/test/java/com/withus/withmebe/gathering/service/GatheringServiceTest.java

🔀 Merge branches Feature/gathering: gathering PR리뷰 리팩토링

---

src/main/java/com/withus/withmebe/gathering/controller/GatheringController.java
src/main/java/com/withus/withmebe/gathering/dto/request/AddGatheringRequest.java
src/main/java/com/withus/withmebe/gathering/dto/request/SetGatheringRequest.java
src/main/java/com/withus/withmebe/gathering/dto/response/AddGatheringResponse.java
src/main/java/com/withus/withmebe/gathering/dto/response/DeleteGatheringResponse.java
src/main/java/com/withus/withmebe/gathering/dto/response/GetGatheringResponse.java
src/main/java/com/withus/withmebe/gathering/dto/response/SetGatheringResponse.java
src/main/java/com/withus/withmebe/gathering/entity/Gathering.java
src/main/java/com/withus/withmebe/gathering/service/GatheringService.java

**AS-IS**
- https://github.com/WithUS-ZB/withme-be/pull/14 
- PR리뷰를 통한 리팩토링
**TO-BE**
- List 조회할경우 페이징처리
- @CurrentAMemberId 통해 멤버아이디 획득
- @Valid 어노테이션 유효성검사 추가
- ResponseDto 분리
- 서비스 메서드 네이밍수정
- DeleteMapping /cancel 중복네이밍 삭제
- String 어노테이션 @NotNull 이 아닌 @NotBlank로 변경
- 필요한 부분만 setter 추가

🔀 Merge branches Feature/gathering: gathering API 리팩토링

---

build.gradle
src/main/java/com/withus/withmebe/member/controller/AuthController.java
src/main/java/com/withus/withmebe/member/controller/AuthSmsController.java
src/main/java/com/withus/withmebe/member/controller/MemberController.java
src/main/java/com/withus/withmebe/member/dto/auth/SigninDto.java
src/main/java/com/withus/withmebe/member/dto/auth/SignupDto.java
src/main/java/com/withus/withmebe/member/dto/auth/request/AuthCodeAndSetPhoneNumberRequestDto.java
src/main/java/com/withus/withmebe/member/dto/auth/request/SendAuthSmsRequestDto.java
src/main/java/com/withus/withmebe/member/dto/auth/response/SendAuthSmsResponseDto.java
src/main/java/com/withus/withmebe/member/dto/member/MemberDetailDto.java
src/main/java/com/withus/withmebe/member/dto/member/MemberInfoDto.java
src/main/java/com/withus/withmebe/member/dto/member/UpdateMemberNickNameDto.java
src/main/java/com/withus/withmebe/member/dto/member/UpdateMemberProfileImgDto.java
src/main/java/com/withus/withmebe/member/entity/Member.java
src/main/java/com/withus/withmebe/member/service/AuthService.java
src/main/java/com/withus/withmebe/member/service/AuthSmsService.java
src/main/java/com/withus/withmebe/member/service/MemberService.java
src/main/java/com/withus/withmebe/member/type/SignupPath.java
src/main/java/com/withus/withmebe/security/config/SecurityConfig.java
src/main/java/com/withus/withmebe/security/domain/CustomUserDetails.java
src/main/java/com/withus/withmebe/security/domain/UserDetailsDomain.java
src/main/java/com/withus/withmebe/security/domain/oauth2/KakaoUserAttributes.java
src/main/java/com/withus/withmebe/security/domain/oauth2/OAuth2UserAttributes.java
src/main/java/com/withus/withmebe/security/domain/oauth2/OAuth2UserAttributesCreater.java
src/main/java/com/withus/withmebe/security/service/CustomUserDetailsService.java
src/main/java/com/withus/withmebe/security/service/OAuth2UserService.java
src/main/resources/application-local.yml
src/main/resources/application.yml
src/test/java/com/withus/withmebe/member/service/AuthSmsServiceTest.java
src/test/java/util/WithMockCustomUserSecurityContextFactory.java

**AS-IS**
- 일반 회원 가입 및 로그인
**TO-BE**
- 카카오 OAuth2 소셜 로그인 기능 추가
- 카카오 로그인 성공 시 DB member에 동일한 이메일이 있는지 확인
- 있으면 해당 member에 대한 토큰 발행
- 없으면 카카오 회원 정보를 이용해 member를 생성 후 해당 member에 대한 토큰 발행

🔀 Merge branches: Feature/oauth2 카카오소셜로그인

---

src/main/java/com/withus/withmebe/security/service/OAuth2UserService.java

**AS-IS**
UserDetailsDomain 필드를 추가했는데 UserDetailsDomain를 생성하는 부분 수정이 부족했음
**TO-BE**
UserDetailsDomain 생성하는 OAuth2UserService에서 맞게 수정

🔀 Merge branches:  Feature/refactor OAuth2UserService - UserDetailsDomain 필드 추가로 인한 수정

---

src/main/java/com/withus/withmebe/common/exception/ExceptionCode.java
src/main/java/com/withus/withmebe/festival/controller/FestivalController.java
src/main/java/com/withus/withmebe/festival/dto/FestivalSimpleInfo.java
src/main/java/com/withus/withmebe/festival/entity/Festival.java
src/main/java/com/withus/withmebe/festival/repository/FestivalRepository.java
src/main/java/com/withus/withmebe/festival/service/FestivalService.java
src/main/java/com/withus/withmebe/security/config/SecurityConfig.java
src/main/resources/application.yml

**AS-IS**
- 서울 축제/문화행사 정보 조회 api 추가
- OpenApi로 서울 축제/문화행사 새벽 4시마다 불러오는 기능 추가
**TO-BE**
- 테스트 코드

🔀 Merge:Feature/festival 축제 행사정보 API 추가

---

src/main/java/com/withus/withmebe/security/domain/CustomUserDetails.java
src/main/java/com/withus/withmebe/security/domain/UserDetailsDomain.java
src/main/java/com/withus/withmebe/security/handler/OAuth2SuccessHandler.java

**AS-IS**
- oauth2 카카오 정보만 확인되면 로그인 되는 형태
**TO-BE**
- oauth2 추가정보 필요한 여부 정보 전달 추가

♻️ Refactor code: oauth2 추가정보 필요한 여부 정보 전달 추가

---

src/test/java/util/security/WithMockCustomUserSecurityContextFactory.java

**AS-IS**
- WithMockCustomUserSecurityContextFactory에서 UserDetailsDomain 변경으로 인한 빌드 오류
**TO-BE**
- WithMockCustomUserSecurityContextFactory에서 UserDetailsDomain 변경으로 인한 빌드 오류 해결

🔀 Merge branches: Feature/oauth2 UserDetailsDomain 변경으로 인한 빌드 오류 해결

---

src/main/java/com/withus/withmebe/search/service/GatheringDocumentService.java
src/main/java/com/withus/withmebe/search/type/Option.java
src/main/java/com/withus/withmebe/search/type/SearchOption.java
src/main/java/com/withus/withmebe/search/type/SearchRange.java
src/test/http/search.http
src/test/java/com/withus/withmebe/search/controller/GatheringDocumentControllerTest.java
src/test/java/com/withus/withmebe/search/service/GatheringDocumentServiceTest.java
src/test/java/util/objectprovider/GatheringDocumentProvider.java

**AS-IS**
- 검색 옵션으로 all 선택 시 검색이 되지 않는 문제 수정
- 모임 검색 API 예시 추가
- 모임 검색 테스트 코드 리팩터링
- GatherigDocumentProvider 변경된 document에 맞게 수정
- GatheringDocumentServiceTest 변경된 document에 맞게 수정
- 모임 검색 테스트 코드 추가
- GatheringDocumentControllerTest 추가

🔀 Merge:Feature/search 검색 옵션 all 버그 수정, 검색 테스트 코드 추가

---

src/main/java/com/withus/withmebe/member/controller/AuthController.java
src/main/java/com/withus/withmebe/member/service/AuthService.java
src/main/java/com/withus/withmebe/security/jwt/filter/JwtAuthenticationFilter.java
src/main/java/com/withus/withmebe/security/jwt/provider/TokenProvider.java
src/main/java/com/withus/withmebe/security/jwt/repository/AccessTokenRepository.java
src/test/http/auth.http
src/test/java/com/withus/withmebe/member/service/AuthServiceTest.java

**AS-IS**
- 로그아웃 기능이 프론트에만 구현이 되어있는 상태
**TO-BE**
- 로그아웃 기능
- 로그인 때 redis에 accessToken 등록
- 로그아웃 때 redis에 등록된 accessToken 삭제
- 토큰 필터에서 redis에 토큰이 있는지 확인로직 추가
- 전체적인 AuthService 테스트 코드 추가
- 로그아웃 api 테스트

🔀 Merge branches Feature/auth 로그아웃 기능 추가

---

src/main/java/com/withus/withmebe/security/config/SecurityConfig.java
src/main/java/com/withus/withmebe/security/handler/OAuth2FailHandler.java

**AS-IS**
- 로그인 페이지 설정 x
- formLogin default 설정
- oAuth2실패에 대한 handler 없음
**TO-BE**
- 로그인 페이지 설정
- 프론트 로그인 페이지로 설정
- formLogin  사용하지 않음으로 인한 disable
- oAuth2 실패 핸들러 생성 및 적용

🔀 Merge branches Feature/refactor security 시큐리티 리펙토링

---

src/main/java/com/withus/withmebe/common/config/S3Config.java
src/main/java/com/withus/withmebe/gathering/controller/GatheringController.java
src/main/java/com/withus/withmebe/gathering/dto/request/AddGatheringRequest.java
src/main/java/com/withus/withmebe/gathering/dto/response/AddGatheringResponse.java
src/main/java/com/withus/withmebe/gathering/entity/Gathering.java
src/main/java/com/withus/withmebe/gathering/service/GatheringService.java
src/main/java/com/withus/withmebe/gathering/service/ImgService.java

- S3 키, 비밀키, 지역 추가 Config 구현
- S3 AWS 클라우드 이미지 업로드 메서드 구현
- 파일추가 할경우 파일.{현재시간}jpg 형식 메서드 구현
- S3 설정 클래스 구현 (S3Config.java)
- 이미지 업로드 서비스 메서드 구현 (ImgService.java)
- 파일 이름에 현재 시간을 추가하는 기능 구현 (changeFileName메서드)
- 이미지 업로드 및 파일 처리를 위해 S3 관련 설정 및 기능이 필요합니다.
- S3Config.java: S3 설정을 관리하는 클래스를 추가합니다.
- ImgService.java: S3에 이미지를 업로드하는 메서드를 추가합니다.
- changeFileName메서드: 파일 이름에 현재 시간을 추가하는 기능을 구현합니다.
- 이미지 업로드 및 파일 처리 관련 기능이 추가됩니다.
- 기존의 파일 처리 로직에는 변경 사항이 없습니다.
- AWS S3와의 연동이 잘 되는지 테스트할 예정입니다.
- 관련 문서 및 참고 자료: https://velog.io/@pizzacolak/Java%EC%97%90%EC%84%9C-AWS-S3%EB%A1%9C-%ED%8C%8C%EC%9D%BC-%EC%97%85%EB%A1%9C%EB%93%9C

🔀 Merge branches: Feature/content-img

---

src/main/java/com/withus/withmebe/gathering/controller/GatheringController.java

✨ Features: 모임추가 컨트롤러 수정

---

src/main/java/com/withus/withmebe/common/exception/ExceptionCode.java
src/main/java/com/withus/withmebe/subscription/controller/SubscriptionController.java
src/main/java/com/withus/withmebe/subscription/dto/SubscriptionResponse.java
src/main/java/com/withus/withmebe/subscription/dto/SubscriptionSimpleInfo.java
src/main/java/com/withus/withmebe/subscription/entity/Subscription.java
src/main/java/com/withus/withmebe/subscription/repository/SubscriptionRepository.java
src/main/java/com/withus/withmebe/subscription/service/SubscriptionService.java
src/test/http/subscription.http

**AS-IS**
- 구독 API 추가
- 구독 등록
- 구독 여부 확인
- 구독 해제
- 내 구독 목록
- 내 구독자 목록
**TO-BE**
- 테스트 코드 추가

🔀 Merge: 구독 API 추가

---

src/main/java/com/withus/withmebe/participation/controller/ParticipationController.java
src/main/java/com/withus/withmebe/participation/service/ParticipationService.java
src/test/http/participation.http
src/test/java/com/withus/withmebe/participation/controller/ParticipationControllerTest.java
src/test/java/com/withus/withmebe/participation/service/ParticipationServiceTest.java

**AS-IS**
- 모임 참여 신청 여부 체크하여 boolean 반환하는 API 추가

✨ Features: 참여 신청 여부 리턴하는 isParticipated API 추가

---

src/main/java/com/withus/withmebe/gathering/controller/GatheringLikeController.java
src/main/java/com/withus/withmebe/gathering/repository/GatheringLikeRepository.java
src/main/java/com/withus/withmebe/gathering/service/GatheringLikeService.java
src/test/http/gatheringlike.http

**AS-IS**
- 모임 글 자신이 좋아여 했는지 여부 체크하는 API 추가

✨ Features: 좋아요 여부 확인 API 추가

---

src/main/java/com/withus/withmebe/participation/dto/MyParticipationSimpleInfo.java
src/main/java/com/withus/withmebe/participation/entity/Participation.java

**AS-IS**
- MyParticipationSimpleInfodp 모임 정보 추가
- 모임 아이디
- 모임 메인 이미지
- 모임 타입
- 모임 상태
- 모임 시간 정보

✨ Features: MyParticipationSimpleInfo 모임 정보 추가

---

src/main/java/com/withus/withmebe/common/config/AsyncConfig.java
src/main/java/com/withus/withmebe/common/exception/ExceptionCode.java
src/main/java/com/withus/withmebe/notification/controller/NotificationController.java
src/main/java/com/withus/withmebe/notification/entity/Notification.java
src/main/java/com/withus/withmebe/notification/event/NotificationEvent.java
src/main/java/com/withus/withmebe/notification/event/NotificationSendEvent.java
src/main/java/com/withus/withmebe/notification/repository/NotificationRepository.java
src/main/java/com/withus/withmebe/notification/response/NotificationResponse.java
src/main/java/com/withus/withmebe/notification/service/NotificationService.java
src/main/java/com/withus/withmebe/notification/type/NotificationType.java

**AS-IS**
- 알림 기능 추가
- 이벤트 리스너 기반으로 알림 필요한 서비스 타입 추가하고 이벤트 발행하면 알림 발송 가능
- 알림 기능 API 추가
-  getSseEmitter : sse 연결 요청
- getUnreadNotifications : 읽지 않은 알림 목록 전체 조회(리스트)
- getNotifications : 모든 알림 목록(페이징)
- setNotificationRead : 알림 읽기 처리
- removeNotification : 알림 삭제(조회 대상에서 제외됨)
**TO-BE**
- 모임 리마인더 추가
- 구독 알림 추가
-  테스트 코드 추가

🔀 Merge: Feature/notification 알림 기능 추가

---

logstash/logstash.conf
src/main/java/com/withus/withmebe/search/controller/GatheringDocumentController.java
src/main/java/com/withus/withmebe/search/document/GatheringDocument.java
src/main/java/com/withus/withmebe/search/repository/GatheringDocumentRepository.java
src/main/java/com/withus/withmebe/search/service/GatheringDocumentService.java
src/main/resources/settings.json

**AS-IS**
- 검색 기능 개선
- 부분 문자열 검색 기능
- 검색어 없을 때 정렬된 페이지 리턴하도록 개선

🔀 Merge:Feature/search 부분 검색 기능 추가

---

src/main/java/com/withus/withmebe/gathering/controller/GatheringLikeController.java
src/main/java/com/withus/withmebe/gathering/dto/response/LikedGatheringSimpleInfo.java
src/main/java/com/withus/withmebe/gathering/entity/GatheringLike.java
src/main/java/com/withus/withmebe/gathering/repository/GatheringLikeRepository.java
src/main/java/com/withus/withmebe/gathering/service/GatheringLikeService.java
src/test/http/gatheringlike.http

**AS-IS**
- 좋아요한 모임 목록 조회 API 추가

🔀 Merge:Feature/gathering like 좋아요한 모임 목록 조회 API 추가

---

src/main/java/com/withus/withmebe/gathering/repository/GatheringRepository.java
src/main/java/com/withus/withmebe/gathering/service/GatheringService.java
src/main/java/com/withus/withmebe/participation/repository/ParticipationRepository.java
src/main/resources/application-local.yml
src/main/resources/application.yml
src/test/http/participation.http

**AS-IS**
- 모임 리마인더 기능 추가
- 테스트 설정으로 15분마다 알림 생성

🔀 Merge:Feature/gathering reminder 모임 리마인더 기능 추가

---

src/main/java/com/withus/withmebe/gathering/dto/response/LikedGatheringSimpleInfo.java
src/main/java/com/withus/withmebe/gathering/entity/GatheringLike.java

**AS-IS**
- 좋아요한 모임 목록에 좋아요 수 정보 추가

✨ Features: 좋아요한 모임 목록에 좋아요 수 정보 추가

---

src/main/resources/application-local.yml
src/main/resources/application.yml

**AS-IS**
도메인 적용에 따라 카카오 로그인 리다이렉트 URI 변경

♻️ Refactor: kakao redirect-uri 수정

---

src/main/java/com/withus/withmebe/common/exception/ExceptionCode.java
src/main/java/com/withus/withmebe/participation/repository/ParticipationRepository.java
src/main/java/com/withus/withmebe/participation/service/ParticipationService.java

**AS-IS**
- 무료 회원이면서 현재 5개 이상의 모임에 참여신청을 했으면 추가적인 신청 불가능하도록 체크

✨ Features: 무료 회원일 때는 최대 5개의 모임에만 참여 신청 가능하도록 체크

---

src/main/java/com/withus/withmebe/common/anotation/DateRangeValidator.java
src/main/java/com/withus/withmebe/common/anotation/GatheringLimit.java
src/main/java/com/withus/withmebe/common/anotation/GatheringLimitAspect.java
src/main/java/com/withus/withmebe/common/anotation/ValidDateRange.java
src/main/java/com/withus/withmebe/gathering/dto/request/AddGatheringRequest.java
src/main/java/com/withus/withmebe/gathering/dto/request/SetGatheringRequest.java
src/main/java/com/withus/withmebe/gathering/dto/response/AddGatheringResponse.java
src/main/java/com/withus/withmebe/gathering/dto/response/DeleteGatheringResponse.java
src/main/java/com/withus/withmebe/gathering/dto/response/GetGatheringResponse.java
src/main/java/com/withus/withmebe/gathering/dto/response/SetGatheringResponse.java
src/main/java/com/withus/withmebe/gathering/entity/Gathering.java
src/main/java/com/withus/withmebe/gathering/repository/GatheringRepository.java
src/main/java/com/withus/withmebe/gathering/service/GatheringService.java

**AS-IS**
- 모든 사용자 모임 개설 제한없음
- 모임 모집기한 유효성 없이 설정
**TO-BE**
- FREE 사용자 모임 개설 5개 이하로 가능
- 모임 모집기한 시작기간이 종료기간보다 늦어질수 없음

✨ Features: 모임 유효성검사 추가(FREE 사용자 모임 개설제한, 모임모집기간)

---

src/main/java/com/withus/withmebe/comment/dto/request/AddCommentRequest.java
src/main/java/com/withus/withmebe/comment/dto/request/SetCommentRequest.java
src/main/java/com/withus/withmebe/comment/entity/Comment.java
src/main/java/com/withus/withmebe/comment/service/CommentService.java
src/test/java/com/withus/withmebe/comment/controller/CommentControllerTest.java
src/test/java/com/withus/withmebe/comment/service/CommentServiceTest.java
src/test/java/util/security/WithMockCustomUser.java
src/test/java/util/security/WithMockCustomUserSecurityContextFactory.java

**AS-IS**
- 유효성 검증 어노테이션 변경 : javax -> jakarta
- 댓글 추가, 수정 요청 시 빈 댓글 허용 되도록 유효성 검증 어노테이션 변경 : NotBlank -> NotNull
- CommentService 클래스 유효성 검증 메서드 리팩터링
- 댓글 수정 시 setter가 아닌 updateComment 메서드 사용하도록 변경
- CommentServiceTest, CommentControllerTest 코드 리팩터링

🔀 Merge:Feature/comment 댓글 기능 코드 리팩터링

---

src/main/java/com/withus/withmebe/festival/service/FestivalService.java
src/main/resources/application-local.yml
src/main/resources/application.yml
src/test/http/festival.http
src/test/java/com/withus/withmebe/festival/controller/FestivalControllerTest.java
src/test/java/com/withus/withmebe/festival/repository/FestivalRepositoryTest.java
src/test/java/com/withus/withmebe/festival/service/FestivalServiceTest.java
src/test/java/util/objectprovider/FestivalProvider.java
src/test/resources/application-test.yml
src/test/resources/sql/festival/data.sql

**AS-IS**
- FestivalService 코드 리팩터링
- 파싱 및 api 요청 메서드 분리
- repository 요청 시간 변수화
- 테스트 코드 추가
- 테스트 데이터 추가

🔀 Merge:Feature/festival 코드 리팩터링 및 테스트 코드 추가

---

src/main/java/com/withus/withmebe/gathering/service/GatheringLikeService.java
src/test/java/com/withus/withmebe/gathering/controller/GatheringLikeControllerTest.java
src/test/java/com/withus/withmebe/gathering/service/GatheringLikeServiceTest.java

**AS-IS**
- 모임 삭제 시 좋아요 삭제 비동기로 처리
- 테스트 코드 리팩터링

🔀 Merge:Feature/gathering like 모임 좋아요 코드 리팩터링

---

src/main/java/com/withus/withmebe/payment/dto/response/AddPaymentResponse.java
src/main/java/com/withus/withmebe/payment/entity/Payment.java
src/main/java/com/withus/withmebe/payment/service/PaymentService.java
src/main/java/com/withus/withmebe/payment/type/Currency.java

**AS-IS**
- AddPaymentResponse에 currency 정보 추가
**TO-BE**
- 테스트 코드 추가
- 승인 요청 결과에 따른 익셉션 처리 추가

♻️ Refactor: 신규 결제 요청 응답에 화폐 정보 추가

---

src/main/java/com/withus/withmebe/payment/dto/request/ApprovePaymentRequest.java
src/main/java/com/withus/withmebe/payment/entity/Payment.java
src/main/java/com/withus/withmebe/payment/service/PaymentService.java

♻️ Refactor: ordrId, ordrMony ordrChk에서 파싱하도록 변경
